/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// It should not be directly modified.

// Import Routes
import { Route as rootRoute } from "./routes/__root";
import { Route as AboutImport } from "./routes/about";
import { Route as ContactImport } from "./routes/contact";
import { Route as HomeImport } from "./routes/home";
import { Route as IndexImport } from "./routes/index";
import { Route as PortfolioImport } from "./routes/portfolio";
import { Route as ServicesImport } from "./routes/services";

// Create/Configure Routes
const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);
const HomeRoute = HomeImport.update({
  path: "/home",
  getParentRoute: () => rootRoute,
} as any);
const ServicesRoute = ServicesImport.update({
  path: "/services",
  getParentRoute: () => rootRoute,
} as any);
const PortfolioRoute = PortfolioImport.update({
  path: "/portfolio",
  getParentRoute: () => rootRoute,
} as any);
const AboutRoute = AboutImport.update({
  path: "/about",
  getParentRoute: () => rootRoute,
} as any);
const ContactRoute = ContactImport.update({
  path: "/contact",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface
declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/home": {
      id: "/home";
      path: "/home";
      fullPath: "/home";
      preLoaderRoute: typeof HomeImport;
      parentRoute: typeof rootRoute;
    };
    "/services": {
      id: "/services";
      path: "/services";
      fullPath: "/services";
      preLoaderRoute: typeof ServicesImport;
      parentRoute: typeof rootRoute;
    };
    "/portfolio": {
      id: "/portfolio";
      path: "/portfolio";
      fullPath: "/portfolio";
      preLoaderRoute: typeof PortfolioImport;
      parentRoute: typeof rootRoute;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutImport;
      parentRoute: typeof rootRoute;
    };
    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree
export const routeTree = rootRoute.addChildren([
  IndexRoute,
  HomeRoute,
  ServicesRoute,
  PortfolioRoute,
  AboutRoute,
  ContactRoute,
]);
